-   id: sql-formatter
    name: sql-formatter
    description: Reformat SQL files with sql-formatter.
    entry: ./run.sh
    require_serial: true
    language: node
    types: [sql]
    additional_dependencies: ["sql-formatter@13.0.0"]
    verbose: true
